public class CredentialsManager {
    public string getTechnicalUser (){
        return '';
    }
    
    public class outputWrpr {
//        public string EndPoint__c{get; set;};
//        public string EndPoint__c;
    }
        public class SystemStatusWrapper {
                public String EndPoint {get;set;}
                public Decimal usedStorage {get;set;}
                public String availableStorage {get;set;}
                public MyEnums.ArchiveStatus status {get; set;}
        }
}